# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f568c0f5e3ed80ef82cf310703905c700a29b7edef45be1e893a39f5d41d7cde438889783d31595979ffa7f33d696f306721ca389b96ed67b953237952e179ae

test:
  secret_key_base: 99663ca59f756a6f9462bed1eed9248755b055812a035c90f5e017a2a5149f57151e964fee7dcc4ce3e87ad97af50c220d7d87d8028f2aeeef4e8ab0ab402550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
